### ISSUE TITLE
Throws when starting

### ISSUE THREAD

**Issue by Moeriki** [nikersify/jay#8]
### System

```
macOS 10.14.6 (18G84)
Node.js v10.16.0
yarn 1.17.3
```

### Steps

1. `yarn global add jay-repl`
2. `jay`

### Expected

REPL starts.

### Actual

```
Error: ENOENT: no such file or directory, open '/Users/moeriki/Library/Caches/jay-repl-nodejs/history'
    at Object.openSync (fs.js:443:3)
    at Object.createHistorian (/Users/moeriki/.config/yarn/global/node_modules/jay-repl/dist/history.js:12:41)
    at main (/Users/moeriki/.config/yarn/global/node_modules/jay-repl/dist/cli.js:94:33)
    at Object.<anonymous> (/Users/moeriki/.config/yarn/global/node_modules/jay-repl/dist/cli.js:170:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
```

**Comment by kbariotis** [comment]
I was just coming to report the same issue on latest macOS for both Node 10 and 12.

**Comment by mikeptweet** [comment]
same on windows 10 with node v12.7.0


![image](https://user-images.githubusercontent.com/1769876/61882249-a9fff580-aed2-11e9-8668-40a7554af1d7.png)

**Comment by kbariotis** [comment]
This seems to be the [offending code](https://github.com/nikersify/jay/blob/master/source/history.ts#L8).

```
// ...
fs.closeSync(fs.openSync(filePath, 'a')) // Touch the history file
// ...
```

Intention was obviously to "touch" the file but I personally never seen this pattern before. Maybe we could do it differently?

**Comment by JCQuintas** [comment]
Same on Windows 10 using Ubuntu WSL1
`Error: ENOENT: no such file or directory, open '/home/jcquintas/.cache/jay-repl-nodejs/history'       
    at Object.openSync (fs.js:448:3)
    at Object.createHistorian (/home/jcquintas/.nvm/versions/node/v11.13.0/lib/node_modules/jay-repl/dist/history.js:12:41)`

**Comment by kbariotis** [comment]
After some digging, I believe the problem is that `openSync` fails to create a file due to a missing parent folder. The folder `/Users/XXX/Library/Caches/jay-repl-nodejs` doesn't exists by default.

**Comment by controversial** [comment]
```
mkdir ~/Library/Caches/jay-repl-nodejs
touch ~/Library/Caches/jay-repl-nodejs/history
```
allows the repl to start for me

**Comment by superhawk610** [comment]
duplicate of #7

**Comment by nikersify** [comment]
fixed in 0.2.1, thanks for the report!

**Comment by mikeptweet** [comment]
This still doesn't work on Windows with node v12.7.0

![image](https://user-images.githubusercontent.com/1769876/61906478-016b8900-af06-11e9-9fa1-316e2a43cd2d.png)

**Comment by nikersify** [comment]
@mikeptweet try removing `C:\Users\Mike\AppData\Local\jay-repl-nodejs\Cache` maybe?

**Comment by mikeptweet** [comment]
That works ... thanks
